# .github/workflows/shot.yml
name: shot

on:
  workflow_dispatch:
    inputs:
      symbol:
        description: 'TradingView symbol (e.g. BINANCE:BTCUSDT)'
        type: string
        required: true
      tfs:
        description: 'CSV of timeframes (e.g. 240,15,1D)'
        type: string
        required: false
        default: '240,15,1D'

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        working-directory: .
        # если package-lock.json отсутствует — замени на:
        # run: npm i

      - name: Shoot ${{ inputs.tfs }}
        env:
          TV_URL: https://chirlickax.github.io/tv-shot/
          SYMBOL: ${{ inputs.symbol }}
          TFS:    ${{ inputs.tfs }}
        run: node tv-shot/shot.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shots
          path: "*.png"
